### ISSUE TITLE
SteedosProvider.requestObject中，统一转换 object, grid 类型字段，生成 subFields 属性

### ISSUE THREAD

**Issue by hotlong** [steedos/app-builder#15]
可以参考 flow.yml
```

  current:
    label: Current
    type: object
    is_wide: true
    blackbox: true
    name: current
  current.modified:
    label: Modification Time of Current
    type: datetime
    readonly: true
    omit: true
    hidden: true
    name: current.modified
  current.modified_by:
    label: Modified Currently by
    type: lookup
    reference_to: users
    readonly: true
    omit: true
    hidden: true
    name: current.modified_by
    filterable: true
  current.created:
    label: Creation Time of Current
    type: datetime
    readonly: true
    omit: true
    hidden: true
    name: current.created
  current.created_by:
    label: Created Currently by
    type: lookup
    reference_to: users
    readonly: true
    omit: true
    hidden: true
    name: current.created_by
    filterable: true
  current.steps:
    label: Current Steps
    type: grid
    readonly: true
    is_wide: true
    name: current.steps
  current.steps.$._id:
    type: text
    omit: true
    readonly: true
    hidden: true
    name: current.steps.$._id
  current.steps.$.name:
    label: Name
    readonly: true
    type: text
    name: current.steps.$.name
  current.steps.$.disableCC:
    label: Disable CC
    type: boolean
    readonly: true
    name: current.steps.$.disableCC
  current.steps.$.allowDistribute:
    label: Can Distribute Instance 
    type: boolean
    readonly: true
    name: current.steps.$.allowDistribute
  current.steps.$.can_edit_main_attach:
    label: Can Edit Main Attach
    type: boolean
    readonly: true
    name: current.steps.$.can_edit_main_attach
  current.steps.$.can_edit_normal_attach:
    label: Can Edit Normal Attach
    type: boolean
    readonly: true
    name: current.steps.$.can_edit_normal_attach
  current.steps.$.distribute_optional_flows:
    label: Workflows of Distribution
    type: lookup
    reference_to: flows
    multiple: true
    omit: true
    hidden: true
    name: current.steps.$.distribute_optional_flows
    filterable: true
  current.steps.$.cc_must_finished:
    label: Must Wait for CC finished
    type: boolean
    readonly: true
    name: current.steps.$.cc_must_finished
  current.steps.$.cc_alert:
    label: Pop up CC Alert
    type: boolean
    readonly: true
    name: current.steps.$.cc_alert
  current.steps.$.allowBatch:
    label: Batch Processing
    type: boolean
    readonly: true
    name: current.steps.$.allowBatch
  current.steps.$.oneClickApproval:
    label: One Click Approval
    type: boolean
    readonly: true
    name: current.steps.$.oneClickApproval
  current.steps.$.oneClickRejection:
    label: One Click Rejection
    type: boolean
    readonly: true
    name: current.steps.$.oneClickRejection
  perms:
    label: Permissions
    type: object
    is_wide: true
    blackbox: true
    name: perms
  perms.users_can_add:
    label: Users that Can Initiate New Request
    type: lookup
    reference_to: users
    multiple: true
    is_wide: true
    name: perms.users_can_add
    filterable: true
  perms.orgs_can_add:
    label: 'Departments that Can Initiate New Request'
    type: lookup
    reference_to: organizations
    multiple: true
    is_wide: true
    name: perms.orgs_can_add
    filterable: true
  perms.users_can_monitor:
    label: Users that Can Read All the Reqests
    type: lookup
    reference_to: users
    multiple: true
    is_wide: true
    name: perms.users_can_monitor
    filterable: true
  perms.orgs_can_monitor:
    label: Departments that Can Read All the Reqests
    type: lookup
    reference_to: organizations
    multiple: true
    is_wide: true
    name: perms.orgs_can_monitor
    filterable: true
  perms.users_can_admin:
    label: Users that Can Read , Relocat, Reassign or Delete  All the Reqests
    type: lookup
    reference_to: users
    multiple: true
    is_wide: true
    name: perms.users_can_admin
    filterable: true
  perms.orgs_can_admin:
    label: Departments that Can Read , Relocat, Reassign or Delete  All the Reqests
    type: lookup
    reference_to: organizations
    multiple: true
    is_wide: true
    name: perms.orgs_can_admin
    filterable: true
```

以上转换之后的结果应该为
```
current:
  type: object
  sub_fields: 
    created_by:
    steps:
      type: grid
      sub_fields: 
        id:
        name: 
...
```
